---
name: Debuild Release
'on':
  release:
    types: published

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  debuild:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: install devscripts
        run: sudo apt-get install equivs devscripts
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo mk-build-deps -ri
      - name: debuild
        run: debuild --no-sign
      - name: import GPG key
        # A secret passphrase is used because the key is stored on disk where
        # it may persist while the passphrase is not.
        run: |
          echo -e "$SIGNING_KEY" | \
              gpg --batch --passphrase "$SIGNING_PASSPHRASE" --import
          gpg --list-secret-keys
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
      - name: debsign
        run: |
          debsign -k12672035D0F1058A -p"gpg --batch --pinentry-mode loopback \
              --passphrase $SIGNING_PASSPHRASE"
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - name: upload
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"
          build_tag="$tag_name-build$(date +'%F-%H-%m-%S-%N')"
          git tag $build_tag
          # https://support.github.com/ticket/personal/0/1996818
          #git push origin $build_tag
          assets=()
          for asset in ../libsml*.{deb,tar.xz,dsc,changes,buildinfo}; do
            assets+=("-a" "$asset")
          done
          hub release edit "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
