---
name: Debuild Release
'on':
  release:
    types: published

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  debuild:
    runs-on: ubuntu-latest
    steps:
      - name: install devscripts
        run: sudo apt-get install equivs devscripts
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo mk-build-deps -ri
      - name: debuild
        run: debuild --no-sign
      - name: create release
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"
		  build_tag="$tag_name-build$(date +'%F-%H-%m-%S-%N')"
          git tag $build_tag
          git push origin $build_tag
          assets=()
          for asset in ../libsml*.{deb,tar.xz,dsc,changes,buildinfo}; do
            assets+=("-a" "$asset")
          done
          hub release edit "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
